### PR TITLE
bugfix/MULTISITE-18510

### PR DESCRIPTION
**Pull request by verbruggenalex**
Please refer to the ticket for questions. If it's clear you can add this to the next release and the platform will follow up with a global fix.

https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-18510

Best regards,
Alkex

### CODE REVIEW

**Comment by libetho** [comment]
@verbruggenalex ,

Do I have to add this feature_sets[reps_xxx][documentation] = '' to all features from the reps-platform?
reps_news, reps_events, ...

**Comment by verbruggenalex** [comment]
Well it's a bug by the platform that trows undefined index errors when it's not set. Its a way for you to bypass the error untill they provide a fix. 
So I wouldn't say its a requirement. But after the starterkit upgrade Behat will fail on it. 

Lets say it can't hurt to define the index in your info files.

**Comment by verbruggenalex** [comment]
PS only features that are an actual feature_set. I think you only have one or two right?

**Comment by libetho** [comment]
Thank for the info. I've merged you PR
Regards

**Pull request merged**
